sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_es1c
sonar.projectName=yovi_es1c

sonar.sources=webapp/src,users/src,gamey/src,auth/src,gameservice/src

sonar.tests=webapp/src,users/__tests__,gamey/src,auth/test,gameservice/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.rs

sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,users/coverage/lcov.info,auth/coverage/lcov.info,gameservice/coverage/lcov.info
sonar.rust.lcov.reportPaths=gamey/lcov.info

sonar.coverage.exclusions=**/index.ts,**/index.js